import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Provider from "./provider";
import {Open_Sans} from 'next/font/google'
import { ClerkProvider } from "@clerk/nextjs";

const MyFont = Open_Sans({subsets:['latin']})

export const metadata: Metadata = {
  title: "GMI AI Kids Story Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={MyFont.className}
      >
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
